# fly.toml file generated for jeremylocatelli-personalsite on 2023-11-29T14:56:54-08:00
app = "jeremylocatelli-personalsite"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
