baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Jeremy Locatelli'
theme = ['ananke', 'hugo-embed-pdf-shortcode']
enableInlineShortcodes = true

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true
