baseURL = 'https://jeremylocatelli-personalsite.fly.dev'
languageCode = 'en-us'
title = 'Jeremy Locatelli'
theme = 'ananke'
enableInlineShortcodes = true

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true
